from advising_portal.models import Faculty, WeekSlot, Course, Section


sections = [
    {
        'section_id': 'CSE1031',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W11').pk,
        'course_id': 'CSE103',
    },
    {
        'section_id': 'ENG1011',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03').pk,
        'course_id': 'ENG101',
    },
    {
        'section_id': 'CSE1061',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01T01').pk,
        'course_id': 'CSE106',
    },
    {
        'section_id': 'ENG1021',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03').pk,
        'course_id': 'ENG102',
    },
    {
        'section_id': 'MAT1011',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S04T04').pk,
        'course_id': 'MAT101',
    },
    {
        'section_id': 'CSE1062',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S04T04').pk,
        'course_id': 'CSE106',
    },
    {
        'section_id': 'MAT1021',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S04T04').pk,
        'course_id': 'MAT102',
    },
    {
        'section_id': 'CSE1101',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01R01T11').pk,
        'course_id': 'CSE110',
    },
    {
        'section_id': 'MAT1041',
        'section_no': 1,
        'section_capacity': 35,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01').pk,
        'course_id': 'MAT104',
    },
    {
        'section_id': 'CHE1091',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W07').pk,
        'course_id': 'CHE109',
    },
    {
        'section_id': 'CSE2091',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03R03T06').pk,
        'course_id': 'CSE209',
    },
    {
        'section_id': 'CSE2511',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01T01R01').pk,
        'course_id': 'CSE251',
    },
    {
        'section_id': 'CSE2001',
        'section_no': 1,
        'section_capacity': 40,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='T01').pk,
        'course_id': 'CSE200',
    },
    {
        'section_id': 'MAT2051',
        'section_no': 1,
        'section_capacity': 40,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03').pk,
        'course_id': 'MAT205',
    },
    {
        'section_id': 'GEN2261',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='T03R03').pk,
        'course_id': 'GEN226',
    },
    {
        'section_id': 'ECO1011',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S05R05').pk,
        'course_id': 'ECO101',
    },
    {
        'section_id': 'CSE2461',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W09').pk,
        'course_id': 'CSE246',
    },
    {
        'section_id': 'CSE2071',
        'section_no': 1,
        'section_capacity': 35,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W11').pk,
        'course_id': 'CSE207',
    },
    {
        'section_id': 'CSE4051',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03R06').pk,
        'course_id': 'CSE405',
    },
    {
        'section_id': 'CSE4052',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W09').pk,
        'course_id': 'CSE405',
    },
    {
        'section_id': 'CSE3021',
        'section_no': 1,
        'section_capacity': 40,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01T01R11').pk,
        'course_id': 'CSE302',
    },
    {
        'section_id': 'CSE3251',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W07').pk,
        'course_id': 'CSE325',
    },
    {
        'section_id': 'CSE3451',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01R01T09').pk,
        'course_id': 'CSE345',
    },
    {
        'section_id': 'STA1021',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M05W05').pk,
        'course_id': 'STA102',
    },
    {
        'section_id': 'CSE3471',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03R09').pk,
        'course_id': 'CSE347',
    },
    {
        'section_id': 'CSE3472',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M03W03W09').pk,
        'course_id': 'CSE347',
    },
    {
        'section_id': 'CSE3601',
        'section_no': 1,
        'section_capacity': 45,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01').pk,
        'course_id': 'CSE360',
    },
    {
        'section_id': 'ENG1012',
        'section_no': 2,
        'section_capacity': 35,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='T05R05').pk,
        'course_id': 'ENG101',
    },
    {
        'section_id': 'ENG1022',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S05R05').pk,
        'course_id': 'ENG102',
    },
    {
        'section_id': 'GEN2031',
        'section_no': 1,
        'section_capacity': 35,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S05T05').pk,
        'course_id': 'GEN203',
    },
    {
        'section_id': 'GEN2032',
        'section_no': 2,
        'section_capacity': 35,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M05W05').pk,
        'course_id': 'GEN203',
    },
    {
        'section_id': 'GEN2141',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01').pk,
        'course_id': 'GEN214',
    },
    {
        'section_id': 'GEN2142',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01R01').pk,
        'course_id': 'GEN214',
    },
    {
        'section_id': 'GEN2101',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03').pk,
        'course_id': 'GEN210',
    },
    {
        'section_id': 'GEN2102',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S04T04').pk,
        'course_id': 'GEN210',
    },
    {
        'section_id': 'BUS2311',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S02T02').pk,
        'course_id': 'BUS231',
    },
    {
        'section_id': 'PHY1091',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01W07').pk,
        'course_id': 'PHY109',
    },
    {
        'section_id': 'PHY2091',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='T01R01R09').pk,
        'course_id': 'PHY209',
    },
    {
        'section_id': 'PHY2092',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01R01').pk,
        'course_id': 'PHY209',
    },
    {
        'section_id': 'CSE4752',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S02T02S06').pk,
        'course_id': 'CSE475',
    },
    {
        'section_id': 'CSE4753',
        'section_no': 3,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03T03T06').pk,
        'course_id': 'CSE475',
    },
    {
        'section_id': 'CSE4771',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03R03T06').pk,
        'course_id': 'CSE477',
    },
    {
        'section_id': 'CSE4871',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S03R03').pk,
        'course_id': 'CSE487',
    },
    {
        'section_id': 'CSE4872',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S02T02').pk,
        'course_id': 'CSE487',
    },
    {
        'section_id': 'CSE4873',
        'section_no': 3,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='T01R01').pk,
        'course_id': 'CSE487',
    },
    {
        'section_id': 'CSE4071',
        'section_no': 1,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M01W01').pk,
        'course_id': 'CSE407',
    },
    {
        'section_id': 'CSE4072',
        'section_no': 2,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='S01T01').pk,
        'course_id': 'CSE407',
    },
    {
        'section_id': 'CSE4073',
        'section_no': 3,
        'section_capacity': 30,
        'total_students': 0,
        'instructor_id': None,
        'routine_id': WeekSlot.objects.get(pk='M05W05').pk,
        'course_id': 'CSE407',
    }
]
